### ISSUE TITLE
Only timeline appears

### ISSUE THREAD

**Issue by Brave28** [GreatApo/AmazfitPaceCalendarWidget#16]
Good afternoon. 
I've intalled the widget, but the calendar does not appear. When I open it i comes only the 
Timeline. I can see all my eventes there, but theres no way to see the dates, the calendar dos not appear. 
Is this actually a bug?

**Comment by GreatApo** [comment]
The Timeline is an activity and not a widget so in the last update I added the code to launch this activity from the app menu (I need to make a new Calendar activity to make the calendar launchable too).

To see the widget you need to enable it first (like you open close the stock widgets from the Amazfit app). To do so you need "Amazmod" or "Springboard Settings". Both apps can enable/disable and re-order watch's widgets.

**Comment by Brave28** [comment]
I'm so sorry, but I don't think I could understand your reply.
The version I installed, Widget Calendar v1.9.4 - Pace/Stratos/Verge (2019-09-02), will or will not launch the calendar?
If so, I could not find the widget to enable it using Amazmod. 
After installing the file you posted here the Timeline appears to me, I lauched it and I use it, but I thought I would also have a calendar.

**Comment by Brave28** [comment]
Hi. It worked. After conecting the Verge to the computer to intall another apk, and then disconnecting it,  the widget appeared in the list of the Amazmod to be enabled. 
I finally got it. 
Thank you 3000.

**Comment by GreatApo** [comment]
:+1: 
Sorry about that, it was a little confusing because I haven't add the calendar in the app menu yet.
I have to fix that bug that Amazmod doesn't show some custom widgets :stuck_out_tongue:
